import { Restaurant } from "./types";

export const mockRestaurants: Restaurant[] = [
  {
    place_id: "ChIJe7vCMSBawokRPf9U6Y1E37k",
    name: "Joe's Pizza",
    address: "7 Carmine St, New York, NY 10014, USA",
    short_address: "7 Carmine St, Manhattan",
    zip_code: "10014",
    neighborhood: "Greenwich Village",
    borough: "Manhattan",
    phone: "(212) 366-1182",
    website: "https://www.joespizzanyc.com/",
    lat: 40.7306,
    lng: -74.0021,
    rating: 4.5,
    review_count: 12847,
    primary_type: "pizza_restaurant",
    delivery_fee: "0",
    delivery_minimum: "15",
    delivery_radius: null,
    ordering_method: "website",
    online_order_url: "https://www.joespizzanyc.com/order",
    editorial_summary: "Cash-only, quick-serve Greenwich Village pizzeria with late-night slices since 1975.",
    delivery_hours: null,
    direct_delivery: 1,
  },
  {
    place_id: "ChIJKxDbe_lYwokRVf__s8CPn-o",
    name: "Di Fara Pizza",
    address: "1424 Avenue J, Brooklyn, NY 11230, USA",
    short_address: "1424 Avenue J, Brooklyn",
    zip_code: "11230",
    neighborhood: "Midwood",
    borough: "Brooklyn",
    phone: "(718) 258-1367",
    website: "https://www.difara.com/",
    lat: 40.6250,
    lng: -73.9614,
    rating: 4.3,
    review_count: 3621,
    primary_type: "pizza_restaurant",
    delivery_fee: "3",
    delivery_minimum: "20",
    delivery_radius: "2 miles",
    ordering_method: "phone",
    online_order_url: null,
    editorial_summary: "Legendary Brooklyn pizzeria where Dom DeMarco hand-makes every pie to order.",
    delivery_hours: null,
    direct_delivery: 1,
  },
  {
    place_id: "ChIJGYvTEkhawokRFAN3AmLW3Fo",
    name: "Halal Guys",
    address: "53rd & 6th Ave, New York, NY 10019, USA",
    short_address: "53rd & 6th Ave, Manhattan",
    zip_code: "10019",
    neighborhood: "Midtown",
    borough: "Manhattan",
    phone: "(347) 527-1505",
    website: "https://thehalalguys.com/",
    lat: 40.7641,
    lng: -73.9793,
    rating: 4.4,
    review_count: 9231,
    primary_type: "restaurant",
    delivery_fee: "2.99",
    delivery_minimum: "10",
    delivery_radius: null,
    ordering_method: "website",
    online_order_url: "https://thehalalguys.com/order",
    editorial_summary: "Iconic halal street cart turned global chain, famous for chicken & gyro over rice.",
    delivery_hours: null,
    direct_delivery: 1,
  },
  {
    place_id: "ChIJ1ckQCXr0wokR3Mj0nsW-x50",
    name: "Caridad Restaurant",
    address: "2230 Grand Concourse, Bronx, NY 10457, USA",
    short_address: "2230 Grand Concourse, Bronx",
    zip_code: "10457",
    neighborhood: "Central Bronx",
    borough: "Bronx",
    phone: "(718) 364-6545",
    website: "https://www.toasttab.com/caridad-restaurant-bronx-2230-grand-concourse-ave",
    lat: 40.856087,
    lng: -73.900317,
    rating: 4.2,
    review_count: 617,
    primary_type: "restaurant",
    delivery_fee: null,
    delivery_minimum: null,
    delivery_radius: null,
    ordering_method: "toast",
    online_order_url: "https://www.toasttab.com/caridad-restaurant-bronx-2230-grand-concourse-ave",
    editorial_summary: "Comfy neighborhood outpost offering homestyle Latin American staples & late hours.",
    delivery_hours: null,
    direct_delivery: 1,
  },
  {
    place_id: "ChIJVVVFNmv0wokRssdueDOUpUk",
    name: "Gotta Getta Pizza",
    address: "1735 Townsend Ave Store A, Bronx, NY 10453, USA",
    short_address: "1735 Townsend Ave, Bronx",
    zip_code: "10453",
    neighborhood: "Central Bronx",
    borough: "Bronx",
    phone: "(347) 732-2200",
    website: null,
    lat: 40.847282,
    lng: -73.911962,
    rating: 4.5,
    review_count: 92,
    primary_type: "pizza_restaurant",
    delivery_fee: null,
    delivery_minimum: null,
    delivery_radius: null,
    ordering_method: "doordash_storefront",
    online_order_url: null,
    editorial_summary: null,
    delivery_hours: null,
    direct_delivery: 1,
  },
  {
    place_id: "ChIJR3Lj9FpZwokRHDmEEl7SwHg",
    name: "Lilia",
    address: "567 Union Ave, Brooklyn, NY 11211, USA",
    short_address: "567 Union Ave, Brooklyn",
    zip_code: "11211",
    neighborhood: "Williamsburg",
    borough: "Brooklyn",
    phone: "(718) 576-3095",
    website: "https://www.lilianewyork.com/",
    lat: 40.7139,
    lng: -73.9510,
    rating: 4.6,
    review_count: 2104,
    primary_type: "italian_restaurant",
    delivery_fee: "5",
    delivery_minimum: "25",
    delivery_radius: "1.5 miles",
    ordering_method: "website",
    online_order_url: "https://www.lilianewyork.com/order",
    editorial_summary: "Upscale Italian spot from chef Missy Robbins known for handmade pastas & seasonal dishes.",
    delivery_hours: null,
    direct_delivery: 1,
  },
  {
    place_id: "ChIJQd0dwuRbwokRXTHh9cKvY7c",
    name: "Sripraphai Thai Restaurant",
    address: "64-13 39th Ave, Woodside, NY 11377, USA",
    short_address: "64-13 39th Ave, Queens",
    zip_code: "11377",
    neighborhood: "Woodside",
    borough: "Queens",
    phone: "(718) 899-9599",
    website: "https://www.sripraphai.com/",
    lat: 40.7441,
    lng: -73.8976,
    rating: 4.4,
    review_count: 4568,
    primary_type: "thai_restaurant",
    delivery_fee: "3",
    delivery_minimum: "15",
    delivery_radius: null,
    ordering_method: "phone",
    online_order_url: null,
    editorial_summary: "Beloved Queens Thai spot celebrated for its authentic flavors and extensive menu.",
    delivery_hours: null,
    direct_delivery: 1,
  },
  {
    place_id: "ChIJ_e7Mo5RYwokRBKP8ds2VFbs",
    name: "Xi'an Famous Foods",
    address: "67 Bayard St, New York, NY 10013, USA",
    short_address: "67 Bayard St, Manhattan",
    zip_code: "10013",
    neighborhood: "Chinatown",
    borough: "Manhattan",
    phone: "(212) 786-2068",
    website: "https://www.xianfoods.com/",
    lat: 40.7156,
    lng: -73.9991,
    rating: 4.4,
    review_count: 5412,
    primary_type: "chinese_restaurant",
    delivery_fee: "0",
    delivery_minimum: "12",
    delivery_radius: null,
    ordering_method: "chownow",
    online_order_url: "https://ordering.chownow.com/order/xian-famous-foods",
    editorial_summary: "Hand-pulled noodles & spicy cumin lamb from this acclaimed chain of fast-casual spots.",
    delivery_hours: null,
    direct_delivery: 1,
  },
  {
    place_id: "ChIJ55nj62z0wokRw9LqK3s7vZo",
    name: "Las Sirenas",
    address: "1896 Jerome Ave, Bronx, NY 10453, USA",
    short_address: "1896 Jerome Ave, Bronx",
    zip_code: "10453",
    neighborhood: "Central Bronx",
    borough: "Bronx",
    phone: "(917) 792-3395",
    website: "https://sirenasrestaurant.com/",
    lat: 40.849962,
    lng: -73.910441,
    rating: 4.2,
    review_count: 262,
    primary_type: "mexican_restaurant",
    delivery_fee: null,
    delivery_minimum: null,
    delivery_radius: null,
    ordering_method: "website",
    online_order_url: null,
    editorial_summary: "Tacos, quesadillas & other Mexican fare in an unpretentious eatery with take-out & delivery.",
    delivery_hours: null,
    direct_delivery: 1,
  },
  {
    place_id: "ChIJq2EPL5VZwokRw5rF-S_kIqI",
    name: "Sal's Pizzeria",
    address: "544 Lorimer St, Brooklyn, NY 11211, USA",
    short_address: "544 Lorimer St, Brooklyn",
    zip_code: "11211",
    neighborhood: "Williamsburg",
    borough: "Brooklyn",
    phone: "(718) 388-6838",
    website: null,
    lat: 40.7095,
    lng: -73.9501,
    rating: 4.3,
    review_count: 301,
    primary_type: "pizza_restaurant",
    delivery_fee: "0",
    delivery_minimum: "10",
    delivery_radius: "1 mile",
    ordering_method: "slice",
    online_order_url: "https://slicelife.com/restaurants/ny/brooklyn/11211/sals-pizzeria",
    editorial_summary: "Old-school neighborhood pizzeria slinging classic New York slices.",
    delivery_hours: null,
    direct_delivery: 1,
  },
  {
    place_id: "ChIJK1oQtfxbwokRFSo4jkKzFQM",
    name: "Nan Xiang Xiao Long Bao",
    address: "38-12 Prince St, Flushing, NY 11354, USA",
    short_address: "38-12 Prince St, Queens",
    zip_code: "11354",
    neighborhood: "Flushing",
    borough: "Queens",
    phone: "(718) 321-3838",
    website: null,
    lat: 40.7617,
    lng: -73.8305,
    rating: 4.2,
    review_count: 3845,
    primary_type: "chinese_restaurant",
    delivery_fee: "5",
    delivery_minimum: "30",
    delivery_radius: null,
    ordering_method: "phone",
    online_order_url: null,
    editorial_summary: "Popular Flushing spot specializing in Shanghai-style soup dumplings and dim sum.",
    delivery_hours: null,
    direct_delivery: 1,
  },
  {
    place_id: "ChIJMcV_5fBTwokR7kqFr_cm_SI",
    name: "Denino's Pizzeria & Tavern",
    address: "524 Port Richmond Ave, Staten Island, NY 10302, USA",
    short_address: "524 Port Richmond Ave, Staten Island",
    zip_code: "10302",
    neighborhood: "Port Richmond",
    borough: "Staten Island",
    phone: "(718) 442-9401",
    website: "https://www.deninos.com/",
    lat: 40.6345,
    lng: -74.1365,
    rating: 4.4,
    review_count: 1102,
    primary_type: "pizza_restaurant",
    delivery_fee: "3",
    delivery_minimum: "15",
    delivery_radius: "3 miles",
    ordering_method: "phone",
    online_order_url: null,
    editorial_summary: "Classic Staten Island tavern-style thin crust pizza since 1937.",
    delivery_hours: null,
    direct_delivery: 1,
  },
  {
    place_id: "ChIJ8YQmC4JZwokRFhkJRBKzCk8",
    name: "Los Tacos No. 1",
    address: "75 9th Ave, New York, NY 10011, USA",
    short_address: "75 9th Ave, Manhattan",
    zip_code: "10011",
    neighborhood: "Chelsea",
    borough: "Manhattan",
    phone: "(212) 256-0343",
    website: "https://www.lostacos1.com/",
    lat: 40.7425,
    lng: -74.0060,
    rating: 4.6,
    review_count: 7321,
    primary_type: "mexican_restaurant",
    delivery_fee: "2",
    delivery_minimum: "15",
    delivery_radius: null,
    ordering_method: "square",
    online_order_url: "https://www.lostacos1.com/order",
    editorial_summary: "Wildly popular taco stand in Chelsea Market known for Tijuana-style tacos & aguas frescas.",
    delivery_hours: null,
    direct_delivery: 1,
  },
  {
    place_id: "ChIJj5mIBR5ZwokRMjUbDW3YOFM",
    name: "Katz's Delicatessen",
    address: "205 E Houston St, New York, NY 10002, USA",
    short_address: "205 E Houston St, Manhattan",
    zip_code: "10002",
    neighborhood: "Lower East Side",
    borough: "Manhattan",
    phone: "(212) 254-2246",
    website: "https://katzsdelicatessen.com/",
    lat: 40.7223,
    lng: -73.9874,
    rating: 4.5,
    review_count: 18432,
    primary_type: "restaurant",
    delivery_fee: "5.99",
    delivery_minimum: "25",
    delivery_radius: null,
    ordering_method: "website",
    online_order_url: "https://katzsdelicatessen.com/shop",
    editorial_summary: "Landmark 1888 deli with famously hand-carved pastrami, salami & other traditional fare.",
    delivery_hours: null,
    direct_delivery: 1,
  },
  {
    place_id: "ChIJOwg_06VPwokRYv534QaPC8g",
    name: "Lucali",
    address: "575 Henry St, Brooklyn, NY 11231, USA",
    short_address: "575 Henry St, Brooklyn",
    zip_code: "11231",
    neighborhood: "Carroll Gardens",
    borough: "Brooklyn",
    phone: "(718) 858-4086",
    website: null,
    lat: 40.6811,
    lng: -73.9966,
    rating: 4.6,
    review_count: 4211,
    primary_type: "pizza_restaurant",
    delivery_fee: null,
    delivery_minimum: null,
    delivery_radius: null,
    ordering_method: "phone",
    online_order_url: null,
    editorial_summary: "BYOB brick-oven pizza in a candlelit Carroll Gardens space. Cash only.",
    delivery_hours: null,
    direct_delivery: 1,
  },
  {
    place_id: "ChIJhWAlrU5ZwokRG8M0gzjRAAQ",
    name: "Mamoun's Falafel",
    address: "119 MacDougal St, New York, NY 10012, USA",
    short_address: "119 MacDougal St, Manhattan",
    zip_code: "10012",
    neighborhood: "Greenwich Village",
    borough: "Manhattan",
    phone: "(212) 674-8685",
    website: "https://www.mamouns.com/",
    lat: 40.7299,
    lng: -74.0003,
    rating: 4.3,
    review_count: 5892,
    primary_type: "restaurant",
    delivery_fee: "0",
    delivery_minimum: "10",
    delivery_radius: null,
    ordering_method: "website",
    online_order_url: "https://www.mamouns.com/order-online",
    editorial_summary: "Cheap, no-frills Middle Eastern counter serve with falafel & shawarma since 1971.",
    delivery_hours: null,
    direct_delivery: 1,
  },
  {
    place_id: "ChIJEQ40dwxbwokRbKEpFMeAYzs",
    name: "SkyIce",
    address: "63-26 Woodhaven Blvd, Queens, NY 11374, USA",
    short_address: "63-26 Woodhaven Blvd, Queens",
    zip_code: "11374",
    neighborhood: "Rego Park",
    borough: "Queens",
    phone: "(718) 205-8855",
    website: "https://www.skyiceny.com/",
    lat: 40.7296,
    lng: -73.8642,
    rating: 4.6,
    review_count: 812,
    primary_type: "ice_cream_shop",
    delivery_fee: "2",
    delivery_minimum: "15",
    delivery_radius: null,
    ordering_method: "toast",
    online_order_url: "https://www.toasttab.com/skyice",
    editorial_summary: "Creative Taiwanese shaved ice & unique desserts in a cheerful Queens shop.",
    delivery_hours: null,
    direct_delivery: 1,
  },
  {
    place_id: "ChIJz0IEhxBTwokRXaGTCI1Mfpw",
    name: "Lee's Tavern",
    address: "60 Hancock St, Staten Island, NY 10305, USA",
    short_address: "60 Hancock St, Staten Island",
    zip_code: "10305",
    neighborhood: "Dongan Hills",
    borough: "Staten Island",
    phone: "(718) 667-9749",
    website: null,
    lat: 40.5895,
    lng: -74.0869,
    rating: 4.5,
    review_count: 645,
    primary_type: "pizza_restaurant",
    delivery_fee: "2",
    delivery_minimum: "12",
    delivery_radius: "2 miles",
    ordering_method: "phone",
    online_order_url: null,
    editorial_summary: "Longtime Staten Island dive bar known for outstanding thin-crust bar pies.",
    delivery_hours: null,
    direct_delivery: 1,
  },
];
